### ISSUE TITLE
  Could not find any downloads that satisfy the requirement docker-registry-driver-gcs

### ISSUE THREAD

**Issue by azr** [dmp42/docker-registry-driver-gcs#2]
Hello there,
I got :
```bash
$ pip install docker-registry-driver-gcs
Collecting docker-registry-driver-gcs
  Could not find any downloads that satisfy the requirement docker-registry-driver-gcs
  No distributions at all found for docker-registry-driver-gcs
```
I could fix this with :
`sudo pip install https://github.com/dmp42/docker-registry-driver-gcs/archive/master.zip`

**Comment by dmp42** [comment]
This driver is deprecated.
Google took over maintenance of it: https://github.com/GoogleCloudPlatform/docker-registry-driver-gcs

I'm going to make that clear in the readme.

**Comment by azr** [comment]
Yes I just saw that too lately.
You should delete it !

http://googlecloudplatform.blogspot.fr/2015/01/secure-hosting-of-private-Docker-repositories-in-Google-Cloud-Platform.html

**Comment by dmp42** [comment]
I updated the README to reflect this - I would rather not delete it though, though definitely sending people to the google re-adopted version.

Thanks anyhow.

Best.
